### ISSUE TITLE
Using `Box` component. 

### ISSUE THREAD

**Issue by muhajirdev** [hupe1980/gatsby-plugin-material-ui#10]
Hey there, 
I am trying to use this with material ui's [Box](https://material-ui.com/utils/box/) . Which and I got error like this . I am using gatsby 2.1.4. 
![image](https://user-images.githubusercontent.com/12745166/53283535-9103e480-377a-11e9-822a-74d8c936c9b7.png)

Any idea why?

Thanks for this plugin btw

**Comment by oliviertassinari** [comment]
The next version of the plugin should support the Box with no issue.
