### ISSUE TITLE
hot reloading doesn't work

### ISSUE THREAD

**Issue by simoneb** [hupe1980/gatsby-plugin-material-ui#12]
Thanks for the plugin, takes away some of the pain of integrating MUI especially with SSR.

While using it I'm noticing that changes to the theme aren't being picked up when running gatsby in development mode. I guess the way gatsby works is it doesn't watch the gatsby-config file.

What I'm doing though, is defining the theme in a file that should be watched by the app, and then require it in the gatsby-config file, besides in other parts of the application. This causes hot reloading to kick in, and yet the plugin doesn't reload the configuration, so changes to the theme are not reproduced in development mode until the app is restarted. Any ideas how to fix this?

**Comment by oliviertassinari** [comment]
@simoneb What version is impacted? Hot reloading should be working with Material-UI v4.0.0-alpha.8
and the @next version of this plugin

**Comment by simoneb** [comment]
@oliviertassinari any chance to have it for a non-alpha version of MUI? I mean MUI has been in alpha for months and we can't really use it in production until it reaches a more stable stage. I'm glad to do the change myself and submit a PR, with some guidance.

**Comment by simoneb** [comment]
@oliviertassinari, to answer your question BTW, I'm running on the `latest` of both MUI and this plugin.

**Comment by oliviertassinari** [comment]
We have no plan for that. v4-beta.0 will be out in a week, v4 stable out in a month. There is close to no advantage at sticking on v3 vs v4-beta.0.

**Comment by simoneb** [comment]
I guess it depends on perspective. For a production application that's using v3, switching to v4 alpha is hardly an option.

**Comment by oliviertassinari** [comment]
@simoneb I agree, I wouldn't switch to an alpha.

**Comment by hupe1980** [comment]
As a workaround, you can use the gatsby-plugin-layout and create your own layout component with MuiThemeProvider:

```javascript
// src/layouts/index.js
import React from 'react'
import { MuiThemeProvider } from '@material-ui/core/styles'

import theme from '../theme'

export default function TopLayout({ children }) {
  return <MuiThemeProvider theme={theme}>{children}</MuiThemeProvider>
}

```

Alternative you can look at a running example with the next version:
https://github.com/hupe1980/gatsby-theme-material-ui

**Comment by simoneb** [comment]
@hupe1980 that's what I'm doing, even though without the layout plugin, I'm just wrapping the root element with the theme provider in gatsby-browser. That doesn't help with SSR though.
