### ISSUE TITLE
WebpackError: TypeError: Cannot read property 'getStyleElement' of undefined

### ISSUE THREAD

**Issue by alexsinfarosa** [hupe1980/gatsby-plugin-material-ui#13]
I am getting this error when I run `gatsby build`. 

```
  18 |
  19 |   const sheets = globalLeak.get(pathname);
> 20 |   setHeadComponents([sheets.getStyleElement()]);
     |                             ^
  21 |   globalLeak.delete(pathname);
  22 | };
  23 |
```

- gatsby-ssr.js:20 Module.onRenderBody
    lib/plugins/gatsby-plugin-material-ui/gatsby-ssr.js:20:29

  - api-runner-ssr.js:43
    lib/.cache/api-runner-ssr.js:43:39

  - api-runner-ssr.js:39 ./.cache/api-runner-ssr.js.module.exports
    lib/.cache/api-runner-ssr.js:39:25

  - develop-static-entry.js:80 Module../.cache/develop-static-entry.js.__webpack    _exports__.default
    lib/.cache/develop-static-entry.js:80:12

  - bootstrap:24 Promise
    lib/webpack/bootstrap:24:1

  - develop-static-entry.js:10 Promise._resolveFromExecutor
    lib/.cache/develop-static-entry.js:10:21

  - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1

  - bootstrap:5 tryCatcher
    lib/webpack/bootstrap:5:1

  - bootstrap:50 MappingPromiseArray._promiseFulfilled
    lib/webpack/bootstrap:50:1

  - api-runner-ssr.js:6 MappingPromiseArray.PromiseArray._iterate
    lib/.cache/api-runner-ssr.js:6:16

  - bootstrap:67 MappingPromiseArray.init
    lib/webpack/bootstrap:67:1

  - bootstrap:19 MappingPromiseArray._asyncInit
    lib/webpack/bootstrap:19:1

  - api-runner-ssr.js:18 _drainQueueStep
    lib/.cache/api-runner-ssr.js:18:1

  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 2.6.0 - /usr/local/bin/fish
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 3.6.4 - /Users/alex/anaconda3/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 65.0
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.3.23 => 2.3.23 
    gatsby-image: ^2.0.39 => 2.0.39 
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-sharp: ^2.0.34 => 2.0.34 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-source-filesystem: ^2.0.29 => 2.0.29 
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18 
  npmGlobalPackages:
    gatsby-cli: 2.5.8

**Comment by oliviertassinari** [comment]
We have a proposed fix in https://github.com/mui-org/material-ui/issues/15391.
