### ISSUE TITLE
Where to put theme file when using this plugin?

### ISSUE THREAD

**Issue by kpennell** [hupe1980/gatsby-plugin-material-ui#16]
I can't seem to get my theme file to have any effect on my components in a Gatsby app.

relevant part of `gatsby-config.js`
 

     `gatsby-plugin-netlify-cms`,
        {
          resolve: `gatsby-plugin-material-ui`,
          options: {
            pathToTheme: 'src/theme.js',
          },

`theme.js`

    import { createMuiTheme } from '@material-ui/core/styles';
    
    import indigo from '@material-ui/core/colors/indigo';
    import pink from '@material-ui/core/colors/pink';
    import red from '@material-ui/core/colors/red';
    
    const theme = createMuiTheme({
      palette: {
        primary: indigo,
        secondary: pink,
        error: red,
      },
      spacing: {
          100
      }
    })
    
    
    export default theme;

within the component:

    imports...
    import { withStyles } from '@material-ui/core/styles';

    const styles = theme => ({
      heroText: {
        color:'white',
        textAlign: 'center',
        lineHeight:7
      },
      mainBlogCopy: {
        marginTop: theme.spacing.unit,
        backgroundColor:theme.palette.primary
      },
    });

    export default withStyles(styles)(AboutPage);

`package.json`

     "dependencies": {
        "@material-ui/core": "^3.9.3",
        "gatsby": "^2.3.24",
        "gatsby-image": "^2.0.34",
        "gatsby-plugin-manifest": "^2.0.24",
        "gatsby-plugin-material-ui": "^1.2.4",

more...

How does one use a theme in another file with this plugin?

**Comment by oliviertassinari** [comment]
@kpennell This plugin doesn't handle the theme. This plugin handles `@material-ui/styles`. You can have a look at https://github.com/hupe1980/gatsby-plugin-material-ui#examples for more detailed example using Material-UI v4.

**Comment by talolard** [comment]
Hi @oliviertassinari 
I took a look over there but couldn't quite figure it out, could you help ? 
It looks like the theme is defined but nothing tells the plugin where it is, is it just assumed to be in theme.js ? 
If so, I'm having the same issue as  @kpennell : The theme.js file is there but has no effect 
Thanks

**Comment by hupe1980** [comment]
Hi @kpennell @talolard 
The plugin has no pathToTheme parameter. The theme is passed in the gatsby-config.js

```javascript
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-material-ui`,
      options: {
        theme: {
           primaryColor: '#9c27b0',
        },
      },
    },
  ],
};
```

In the next version for Material-UI v4, the theme support will be completely removed. 
What it might look like, you can see here:
https://www.npmjs.com/package/gatsby-theme-material-ui
https://github.com/mui-org/material-ui/tree/next/examples/gatsby-next

**Comment by kpennell** [comment]
Thanks for clarifying. I think I'm confused because when I search through
projects using this plugin, I find like 3-4 different implementation
styles, including the pathtotheme parameter (used by some).

**Comment by hupe1980** [comment]
Ok! ! I will close the issue then

**Comment by kpennell** [comment]
@hupe1980 so the pathtotheme thing was another project? Or just someone implemented it differently? Is it possible to have a file for it?

**Comment by hupe1980** [comment]
@kpennell 
Yes, the parameter was only available in another project. If you still need the functionality, you can use the following workaround:
https://github.com/hupe1980/gatsby-plugin-material-ui/issues/12#issuecomment-484962819

The gatsby-config.js must then look like this
```javascript
// gatsby-config.js
...
{
      resolve: `gatsby-plugin-material-ui`,
      options: {
        theme: {
          typography: {
            useNextVariants: true,
          },
        },
      },
    }
...
```

**Comment by kpennell** [comment]
Thanks

**Comment by kpennell** [comment]
@hupe1980 I'm noticing that the theme option in the gatsby-config.js isn't doing anything. Is there anyway besides #12 that would work for this? I'm using gatsby-browser and ssr and don't want to create a bunch of headache.

**Comment by kpennell** [comment]
nevermind: https://stackoverflow.com/questions/55821752/where-to-put-theme-file-when-using-the-gatsby-plugin-material-ui-with-gatsby

**Comment by hupe1980** [comment]
The theme option is no longer available in v4.
You can use a local plugin (see [gatsby-plugin-top-layout](https://github.com/mui-org/material-ui/tree/master/examples/gatsby)) or you can use [gatsby-theme-material-ui](https://github.com/hupe1980/gatsby-theme-material-ui/tree/master/packages/gatsby-theme-material-ui)
