### ISSUE TITLE
2.0.0-alpha.6 flashing unstyled componentts

### ISSUE THREAD

**Issue by alanpog** [hupe1980/gatsby-plugin-material-ui#18]
Tested only with [the gatsby-material-kit-react starter](https://www.gatsbyjs.org/starters/WebCu/gatsby-material-kit-react/), so not sure how specific to its config (material-ui version for example) this issue is. But one can easily toggle between having the unstyled flash or not by switching between `@next` (`2.0.0-alpha.6)` and `@latest` (`1.2.4`).

I'm afraid this may bite more people than necessary despite the `alpha` label because:
- this repo's `README` only mentions the `@next` install now; and
- there's currently no installation instructions on the [plugin page at Gatsby's website](https://www.gatsbyjs.org/packages/gatsby-plugin-material-ui/?=material) (it's blank)

Related discussion: https://github.com/creativetimofficial/material-kit-react/issues/51#issuecomment-489219402

**Comment by oliviertassinari** [comment]
@alanpog The Gatsby example on Material-UI side doesn't use this plugin in v3. It does use it in v4. I would encourage to replicate the example.

**Comment by alanpog** [comment]
@oliviertassinari indeed I can confirm that the same example with `@next` works fine with `material-ui v4`. That's great. However, given that `v4` is still in beta it'd probably help other people like me if the docs have a short mention that for `v3` one should use `@latest` instead.

**Comment by oliviertassinari** [comment]
@hupe1980 What do you think of adding a peer dependency on Material-UI in https://github.com/hupe1980/gatsby-plugin-material-ui/blob/237d40476c7a5345167c775a6c2b2c42cc66980f/package.json#L23
 ?

**Comment by hupe1980** [comment]
Yes, that's a good point. I adjusted it
