### ISSUE TITLE
Support for prefixing and minification 

### ISSUE THREAD

**Issue by hupe1980** [hupe1980/gatsby-plugin-material-ui#21]
https://next.material-ui.com/getting-started/supported-platforms/#css-prefixing

@oliviertassinari Should we do that in the plugin? What do you think?

**Comment by oliviertassinari** [comment]
@hupe1980 This sounds like a great idea. The downside is about generation performance. I would probably add a flag to disable it. The Material-UI documentation can be a great source of inspiration for the actual implementation. We handle it with Next.js using PostCSS.

**Comment by oliviertassinari** [comment]
Nice!
