### ISSUE TITLE
Material-UI v3 and Styled Components? Can they play nicely together when using this plugin?

### ISSUE THREAD

**Issue by dante-blitz** [hupe1980/gatsby-plugin-material-ui#22]
Hi there,

I would like to use Material UI v3 with Styled Components. I have read this package's issues and readme and am not too clear if it can be achieved with the plugin. Can you please provide some clarity. 

If it can be achieved is it possible to also provide a detailed example.

Many thanks in advance.

**Comment by oliviertassinari** [comment]
@dante-blitz It definitely works with v4. Do you really need to rely on v3?

**Comment by dante-blitz** [comment]
I'm reluctant to use v4 on an important client project as its still in alpha. My plan is to use v3 for the time being and upgrade once a stable v4 release is available.

**Comment by oliviertassinari** [comment]
@dante-blitz We are in v4.0.0-beta.1 now. v4 stable will land May 23rd.

**Comment by dante-blitz** [comment]
Ill give v4 a chance from now then. Can you please provide detail to get both working.

Is it simply a case of setting up gatsby-config as specified in the readme? are any other steps required?

**Comment by oliviertassinari** [comment]
Nothing more is needed.

**Comment by dante-blitz** [comment]
Excellent. I'll give it a try. Thanks for your help.
