### ISSUE TITLE
What options can be passed in the config??

### ISSUE THREAD

**Issue by skdigital** [hupe1980/gatsby-plugin-material-ui#3]
The documentation is very limited, could you expand on how to use this theme/plugin by improving the documentation? I am really unsure as to what config options I can pass etc..

**Comment by walleXD** [comment]
The `theme` object just gets passed to the `MuiThemeProvider`.  Take a peek [here](https://github.com/hupe1980/gatsby-plugin-material-ui/blob/37f4534ff731f5e65c72313a163a87d3704f7ca9/src/gatsby-ssr.js#L37)

**Comment by JeanLoureiro** [comment]
I find it easier to understand if you look [here](https://github.com/hupe1980/gatsby-plugin-material-ui/blob/37f4534ff731f5e65c72313a163a87d3704f7ca9/src/gatsby-ssr.js#L10) and then in the [documentation](https://material-ui.com/customization/themes/) 

This is how it worked for me
`
plugins: [
        {
            resolve: `@wapps/gatsby-plugin-material-ui`,
            options: { 
                theme: {
                    palette: {
                        primary: {
                            main: '#f1f1f1', // new color here 
                        } 
                    },
                },
            },
        }
    ]
}
`
