### ISSUE TITLE
Doesn't work on starting on material-ui 4.2.1

### ISSUE THREAD

**Issue by ekremkenter** [hupe1980/gatsby-plugin-material-ui#36]
After upgrading material ui to 4.2.1, theme is not applied. Gatsby and material ui versions are,
```
"@material-ui/core": "4.2.1",
"@material-ui/icons": "4.2.1",
"@material-ui/styles": "4.2.1",
"gatsby": "^2.13.32",
"gatsby-plugin-material-ui": "^2.1.4",
```
It is working fine on material-ui 4.2.0.

**Comment by oliviertassinari** [comment]
@ekremkenter Look for duplicates of @material-ui/styles in your dependency tree.

**Comment by hupe1980** [comment]
@oliviertassinari Our readme says that the plugin should be installed together with @material-ui/styles: 

> npm install gatsby-plugin-material-ui @material-ui/styles

If you install @material-ui/core now, you have @material-ui/styles twice

```bash 
yarn list --pattern @material-ui
yarn list v1.16.0
├─ @material-ui/core@4.3.0
│  └─ @material-ui/styles@4.2.1
├─ @material-ui/icons@4.2.1
├─ @material-ui/styles@4.3.0
├─ @material-ui/system@4.3.1
├─ @material-ui/types@4.1.1
└─ @material-ui/utils@4.1.0
```

**Comment by oliviertassinari** [comment]
I will use the reverse approach in the next release: bump all the dependency at once.

**Comment by ekremkenter** [comment]
Removing @material-ui/styles worked. core was not depending styles package on 4.2.0 but it depends now.
