### ISSUE TITLE
.cache published on npm

### ISSUE THREAD

**Issue by oliviertassinari** [hupe1980/gatsby-plugin-material-ui#38]
@hupe1980 I have noticed that we publish a `.cache` folder in the npm package. It's strange: https://unpkg.com/browse/gatsby-plugin-material-ui@2.1.5/.cache/. Do you have this folder name configured in your global gitignore?

**Comment by hupe1980** [comment]
@oliviertassinari The folder name is configured in the .gitignore:
https://github.com/hupe1980/gatsby-plugin-material-ui/blob/5d682933304c1fecf0a136c5847605bba648842b/gatsby-plugin-material-ui/.gitignore#L71

I would say we also need to configure the cache folder in .npmignore

**Comment by oliviertassinari** [comment]
For the context, I have discovered this curiosity upgrading the dependency in a Gatsby project:

>  ERROR  Failed to compile with 1 errors                                                                                                                23:50:51
This dependency was not found:
> * /Users/hupe/Workspace/wapps/gatsby-plugin-material-ui/e2e-tests/development-runtime/src/styles-provider-props in ./node_modules/gatsby-plugin-material-ui/.cache/styles-provider-props.js

Then I don't understand who it's happening. I would expect npm to use this gitignore file if no npmignore file can be found.

**Comment by hupe1980** [comment]
We already have a [.npmignore](https://github.com/hupe1980/gatsby-plugin-material-ui/blob/master/gatsby-plugin-material-ui/.npmignore).

**Comment by oliviertassinari** [comment]
Then the gitignore is ignored, as well as the .cache rule, mistery solved :).

**Comment by hupe1980** [comment]
@oliviertassinari I fixed the issue.

**Comment by oliviertassinari** [comment]
Well done!
