### ISSUE TITLE
Make ThemeProvider available in pages

### ISSUE THREAD

**Issue by tw1t611** [hupe1980/gatsby-plugin-material-ui#39]
Hi,

I recently encountered a problem on using Material UI's ThemeProvider with Gatsby.
Since there is no root component, it's not possible to wrap the whole App with the ThemeProvider.  Therefor I do wrap the layout component, which gets imported into the pages. In consequence I need to implement a workaround for all pages, to access the theme.

ThemeProvider in Layout:
```javascript
const Layout = ({ children }) => {
  const classes = useStyles()
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Header />
      <main className={classes.content}>
        <div className={classes.toolbar} />
        {children}
      </main>
      <Footer />
    </ThemeProvider>
  )
}
```

Page workaround:
```javascript
import theme from "../components/theme"

const Theme = theme
const useStyles = makeStyles(Theme => ({
// mui styles
}))
```

Is there a better way to use material ui ThemeProvider with gatsby?
Would it be possible to provide a injectIntoPages option in this plugin?

**Comment by hupe1980** [comment]
@tw1t611 Take a look at the example section in the README

**Comment by tw1t611** [comment]
I did, what did I miss?
I found the theme option in v3, is it still available in v4? Does it use the mui defaults as a base?

**Comment by hupe1980** [comment]
The theme option is no longer available in v4. 
You can use a local plugin (see [gatsby-plugin-top-layout](https://github.com/mui-org/material-ui/tree/master/examples/gatsby)) or you can use [gatsby-theme-material-ui](https://github.com/hupe1980/gatsby-theme-material-ui/tree/master/packages/gatsby-theme-material-ui)

**Comment by tw1t611** [comment]
Thank you very much! [gatsby-theme-material-ui](https://github.com/hupe1980/gatsby-theme-material-ui/tree/master/packages/gatsby-theme-material-ui) is exactly what I was looking for. Don't know, why I had not found it before.
