### ISSUE TITLE
add support for @material-ui/styles

### ISSUE THREAD

**Issue by walleXD** [hupe1980/gatsby-plugin-material-ui#4]
Material-Ui has a new theme engine. We should provide an option to the newer one which is available through the `@material-ui/styles` package

**Comment by hupe1980** [comment]
@walleXD @oliviertassinari I started with the implementation... You can try it with npm install @wapps/gatsby-plugin-material-ui**@next**

**Comment by oliviertassinari** [comment]
The server-side API isn't finalized yet. I want to hide as many moving part as possible, also make customizing the injection point easier.

**Comment by oliviertassinari** [comment]
@hupe1980 Hi, I would like to provide first-class support for Gatsby with Material-UI. I order to achieve that, I think that we should make the [material-ui gatsby example](https://github.com/mui-org/material-ui/tree/next/examples/gatsby) use a plugin over a hand-coded solution. It will be more future proof (I will look into the same plugin approach for Next.js or really simplify the SSR API).
What do you think about it?

**Comment by oliviertassinari** [comment]
@hupe1980 Do you use Gitter? I would like to chat.

**Comment by hupe1980** [comment]
@oliviertassinari Yes, i use Gitter. My nickname is hupe1980.

**Comment by oliviertassinari** [comment]
I have started working on a first-class support of Material-UI v4-alpha for Gatsby: https://github.com/mui-org/material-ui/tree/next/examples/gatsby-next. I will move the changes to this package once it's complete.

**Comment by oliviertassinari** [comment]
Alright, it's done. I think that we can move https://github.com/mui-org/material-ui/tree/next/examples/gatsby-next/plugins/gatsby-plugin-material-ui this local plugin code to here. For people who wants to use styled-components at the same time, they can do:
```jsx
module.exports = {
  plugins: [
    'gatsby-plugin-top-layout',
    {
      resolve: 'gatsby-plugin-material-ui',
      // If you want to use styled components you should change the injection order.
      options: {
        stylesProvider: {
           injectFirst: true,
        },
      },
    },
    // If you want to use styled components you should add the plugin here.
    'gatsby-plugin-styled-components',
    'gatsby-plugin-react-helmet',
  ],
  siteMetadata: {
    title: 'My page',
  },
};
```

**Comment by oliviertassinari** [comment]
The support was added in the next version of the plugin.
