### ISSUE TITLE
"gatsby build" major problems? Things look really different? Check your versions!

### ISSUE THREAD

**Issue by kpennell** [hupe1980/gatsby-plugin-material-ui#41]
![image](https://user-images.githubusercontent.com/1060385/66918685-2f053180-f020-11e9-9ca8-8d6bc9ed738a.png)

If your gatsby build seems to just blow everything up and the final results looks terrible, check that you have the right material-ui + this plugin installed.

whew...

**Comment by oliviertassinari** [comment]
Did you find a solution?

**Comment by kpennell** [comment]
upgrading versions on this plugin! using v4 material-ui and the 2.x of this plugin now

**Comment by oliviertassinari** [comment]
Great! Thanks for the feedback
