### ISSUE TITLE
Minimize Bundle Size procedures recommended?

### ISSUE THREAD

**Issue by valoricDe** [hupe1980/gatsby-plugin-material-ui#44]
In https://github.com/mui-org/material-ui/blob/master/docs/src/pages/guides/minimizing-bundle-size/minimizing-bundle-size.md it is recommend to use babel plugins to ensure that

```
import { Button, TextField } from '@material-ui/core';
```
are transpiled to:
```
import Button from '@material-ui/core/Button';
import TextField from '@material-ui/core/TextField';
```

I wonder if this also holds true for this the combination of gatsby and this plugin

**Comment by oliviertassinari** [comment]
@valoricDe The only advantage is dev start-up time. For the core package, the impact is not very noticeable, maybe a dozen of seconds.

**Comment by valoricDe** [comment]
Ok, thank you for your feedback
