### ISSUE TITLE
Support Yarn PNP / Plug'n'Play

### ISSUE THREAD

**Issue by nolandg** [hupe1980/gatsby-plugin-material-ui#46]
It seems this package tries to write to a `.cache` folder within `node_modules`. Using Yarn 2 Plug'n'Play this doesn't work as that is a read-only virtual file system so the build fails. Can you do like most other modules and store your `.cache` in the project directory instead? Or am I missing something?

Thanks for the great plugin!

"gatsby-plugin-material-ui" threw an error while running the onPreBootstrap lifecycle:

````sh
EROFS: read-only filesystem, mkdir '/node_modules/gatsby-plugin-material-ui/.cache'

  36 | 
  37 |   if (!fs.existsSync(dir)) {
> 38 |     fs.mkdirSync(dir);
     |        ^
  39 |   }
  40 | 
  41 |   fs.writeFileSync(dir + "/styles-provider-props.js", module);

File: .yarn/$$virtual/gatsby-plugin-material-ui-virtual-1b8deca526/0/cache/gatsby-plugin-material-ui-npm-2.1.6-fc64177c4c-2.zip/node_modules/gatsby-plugin-material-ui/gatsby-node.js:38:8

  Error: EROFS: read-only filesystem, mkdir '/node_modules/gatsby-plugin-material-ui/.cache'
  - .pnp.js:27535 makeError
    /home/noland/projects/acdc-shop/.pnp.js:27535:24
````

**Comment by nolandg** [comment]
The workaround is to force Yarn to unplug this module: https://yarnpkg.com/cli/unplug
by running `yarn unplug gatsby-plugin-material-ui` before `yarn build gatsby`

**Comment by hugoelizandro** [comment]
The problem started to occur with the new version of node, I had to rollback to 13.13.0

**Comment by oliviertassinari** [comment]
Do we have a reproduction to investigate?

**Comment by hupe1980** [comment]
We have to switch to Gatsby's cache logic. I will create a PR
