### ISSUE TITLE
When to use the plugin vs. the theme?

### ISSUE THREAD

**Issue by dandv** [hupe1980/gatsby-plugin-material-ui#50]
Thanks @hupe1980 for publishing both. How should new users choose between using this plugin, vs. [the theme](https://github.com/hupe1980/gatsby-theme-material-ui)?

**Comment by oliviertassinari** [comment]
@dandv It depends on what you want to optimize for. I think that the simplest is to start with the theme and "eject" if you need more control, but it's only my understanding on the problem.

**Comment by dandv** [comment]
I want a reliable solution (e.g. [no FOUC](https://github.com/gatsbyjs/gatsby/issues/15097)) that I can start rapidly with. I only want to customize the colors in the palette.

**Comment by oliviertassinari** [comment]
@dandv Here is a detailed version I'm aware of:

1. gatsby-plugin-material-ui: solve the FOUC, auto prefix, and minification.
2. gatsby-theme-material-ui: solve 1. and: loading font, helper to apply theme, styled Link component, meta viewport.

**Comment by hash** [comment]
What will happen if both plugins are used, do they work together? Do they should be used together? 
Should not be used together?

**Comment by oliviertassinari** [comment]
The theme already use the plugin internally. I would assume users shouldn't use them together.

**Comment by oliviertassinari** [comment]
…

**Comment by erin-doyle** [comment]
This would be great info to add to the READMEs of both repos and the Gatsby plugin listings.
