### ISSUE TITLE
Can you use without advanced configuration?

### ISSUE THREAD

**Issue by stevemarksd** [hupe1980/gatsby-plugin-material-ui#52]
Hi!

I was trying to use this plugin but without the jss insertion specified here https://www.gatsbyjs.org/packages/gatsby-plugin-material-ui/#advanced you can't override styles properly. I think this should be done by default instead of requiring every project to setup another extra js file of config.

**Comment by oliviertassinari** [comment]
What's your use case?

**Comment by stevemarksd** [comment]
Just override a style with emotion.js. You can't use this plugin out of the box, you need to use advanced mode. I think that should be by default as most of the people need to override material ui styles.

**Comment by oliviertassinari** [comment]
Ok, thanks. I have added your comment in https://trello.com/c/QZN9Zz69/2557-https-githubcom-mui-org-material-ui-issues-20776issuecomment-619633328. We might change the default injection order in v5, we will see.
