### ISSUE TITLE
Font requested a second time upon hydration.

### ISSUE THREAD

**Issue by cbravo** [hupe1980/gatsby-plugin-material-ui#55]
I am using this plugin and I am experiencing a strange issue where my font is being requested a second time after the page loads on the build.

My setup is like the following:
```
// gatsby-config.js
plugins: [
    {
      resolve: `gatsby-plugin-material-ui`,
      options: {
        stylesProvider: {
          injectFirst: true,
        },
      },
    },
```
```
// ThemeProvider.js

import {  createMuiTheme, ThemeProvider as MuiThemeProvider, } from '@material-ui/core/styles';
import { ThemeProvider as ScThemeProvider } from 'styled-components';

const theme = createMuiTheme({
  typography: {
    fontFamily: 'Raleway, Arial',
  },
  overrides: {
    MuiCssBaseline: {
      '@global': {
        '@font-face': [raleway],
      },
    },
  },
});

const ThemeProvider = ({children }) => {
  return (
    <MuiThemeProvider theme={theme}>
      <ScThemeProvider theme={theme}>{children}</ScThemeProvider>
    </MuiThemeProvider>
  );
};
export default ThemeProvider;
```
```
// ... gatsby-browser.js and gatsby-ssr.js

exports.wrapPageElement = ({ element }) => (
  <ThemeProvider>
    <CssBaseline />
    {element}
  </ThemeProvider>
);
```

With this setup I am seeing the font load on the server-side and the once again once react hydrates:
 
![image](https://user-images.githubusercontent.com/5489389/81848179-b701da00-9522-11ea-819e-38991f622047.png)

The weird thing is that sometimes it DOESN'T load twice.... sometimes it loads once as expected. Am I doing something wrong here?

if you want to see the live website checkout https://coivd19.klick.com

**Comment by oliviertassinari** [comment]
@cbravo How is the issue related to the package? Also, does it happen with the network cache enabled (default)?

**Comment by cbravo** [comment]
Let me double check if caching is somehow related. I thought maybe it was related to  `gatsby-plugin-material-ui` because maybe I had misconfigured it and was causing some kind of problem during hydration...

**Comment by cbravo** [comment]
@oliviertassinari ...facepalm.... 

![image](https://user-images.githubusercontent.com/5489389/82055458-863eb380-968e-11ea-803b-5221f7988d57.png)

you are right...I didn't realize I had disable caching turned on whenever I had my inspector open which is why it only seemed to happen some of the time. Turning that off fixes the issue.

Thank you for your response and pointing me in the right direction!
 I am going to go and try not to die of embarrassment :P
