### ISSUE TITLE
Error onPreBootstrap lifecycle

### ISSUE THREAD

**Issue by janvarsa** [hupe1980/gatsby-plugin-material-ui#62]
I recently started getting the error below when I run "gatsby develop", although the build step completes successfully afterwards (unsure if this will break a Netlify deploy however):

 ERROR #11321  PLUGIN

```
"gatsby-plugin-material-ui" threw an error while running the onPreBootstrap lifecycle:

The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null

  39 |   }
  40 |
> 41 |   fs.writeFileSync(dir + "/styles-provider-props.js", module);
     |      ^
  42 | };

File: node_modules\gatsby-plugin-material-ui\gatsby-node.js:41:6
```

**Comment by andrewnoyes** [comment]
@janvarsa What version of the plugin are you using? We ran into this same issue, and upgrading to the latest version of the plugin fixed it for us. Pretty sure this is the relevant [commit](https://github.com/hupe1980/gatsby-plugin-material-ui/commit/147128a12a159d1833365cc782a0b8cce49cee11).

**Comment by megane42** [comment]
I had used v2.1.6 and after upgrading to v2.1.10 the issue was fixed. Thank you so much 💯💯💯
