### ISSUE TITLE
How can I get this to work?

### ISSUE THREAD

**Issue by yehudamakarov** [hupe1980/gatsby-plugin-material-ui#7]
I tried to follow the instructions in the example, but the elements I try to render don't have the default colors of the primary and secondary colors I give to the plugin syntax. 
```
{
    resolve: `@wapps/gatsby-plugin-material-ui`,
    options: {
        theme: {
            primaryColor: '#D32F2F',
            secondaryCOlor: '#90A4AE',
        }
    },
},
```
Even if I pass the primary red and secondary grey, the theme still has purple in it.
Should be like this: https://material.io/tools/color/#!/?view.left=0&view.right=1&primary.color=D32F2F&secondary.color=90A4AE
I have to be missing something, any help is appreciated.

**Comment by yehudamakarov** [comment]
I’m going to try changing it up. I think I used a theme generator from somewhere. I’ll let you know soon.

**Comment by n-batalha** [comment]
@yehudamakarov all good and can be closed? 

Note also that I think even if an issue, this would be in the material-ui package itself, not this plugin that just passes the config to it.

**Comment by yehudamakarov** [comment]
Hey, I just found that project, tried what you suggested, and voila. The theme exporter I was using gave the first syntax to me. 

Let's close it, and thank you for taking the time. I agree about it being an issue with them, but I wanted to get this plugin working that's why I asked for suggestions here.

Thanks 👍
