### ISSUE TITLE
Material UI V5 support?

### ISSUE THREAD

**Issue by ZLevine** [hupe1980/gatsby-plugin-material-ui#70]
Does this plugin work with Material UI V5 (alpha)? The docs only reference V3 and V4. Thanks!

**Comment by oliviertassinari** [comment]
@ZLevine This plugin is no longer needed in MUI v5.

**Comment by ZLevine** [comment]
How so? I presume an MUI plugin would still be useful as it would abstract away a lot of things like server side stylesheets, ThemeProvider, etc.

**Comment by oliviertassinari** [comment]
@ZLevine This is what Gatsby commonly references as a theme. See https://github.com/hupe1980/gatsby-theme-material-ui for this problem.

**Comment by oliviertassinari** [comment]
@ZLevine Gatsby uses the notion of ["theme"](https://www.gatsbyjs.com/docs/themes/what-are-gatsby-themes/) for the solution you are interested in. See https://github.com/hupe1980/gatsby-theme-material-ui.

**Comment by ZLevine** [comment]
Ah thanks, I didn't know there was a Gatsby theme for MUI!

**Comment by oliviertassinari** [comment]
Actually, I was wrong. We still need a plugin for Gatsby with Material-UI v5 based on https://github.com/mui-org/material-ui/issues/26561#issuecomment-855286153. Now, there is an extra layer of complexity, we support emotion and styled-components. So while we could argue, just use these plugins, we could also argue that these plugins do it wrong.

**Comment by ZLevine** [comment]
Gotcha. Yeah, it seems that because of all the complexity MUI requires for initial setup, a plugin would be preferable. Themes are great to "bootstrap" based on the plugin but a plugin seems more appropriate here.

**Comment by oliviertassinari** [comment]
We can start from https://github.com/mui-org/material-ui/tree/next/examples/gatsby/plugins/gatsby-plugin-mui-emotion

**Comment by hupe1980** [comment]
I have prepared the next branch accordingly

**Comment by oliviertassinari** [comment]
@hupe1980 Awesome, I have left a few comments on https://github.com/hupe1980/gatsby-plugin-material-ui/commit/c18fff2365be09cfa7f5437671a4d2adc0d414ae if you want to push it the extra mile. My main concern with Gatsby is the trend it's on: https://npm-stat.com/charts.html?package=gatsby&package=next&package=react-scripts&from=2020-08-07&to=2021-08-07.

**Comment by hupe1980** [comment]
The plugin can now also be used for V5:
```
npm install gatsby-plugin-material-ui@next @emotion/react
```
Only emotion is supported at the moment!

**Comment by ZLevine** [comment]
> The plugin can now also be used for V5:
> 
> ```
> npm install gatsby-plugin-material-ui@next @emotion/react
> ```
> 
> Only emotion is supported at the moment!

This is fantastic news! Will test this out soon.


> @hupe1980 Awesome, I have left a few comments on [c18fff2](https://github.com/hupe1980/gatsby-plugin-material-ui/commit/c18fff2365be09cfa7f5437671a4d2adc0d414ae) if you want to push it the extra mile.
> 
> My main concern with Gatsby is the trend it's on: https://npm-stat.com/charts.html?package=gatsby&package=next&package=react-scripts&from=2020-08-07&to=2021-08-07.

Yeah—from experience, Gatsby SSG can be a pain for larger sites and they don't have _true_ SSR like Next does. For smaller sites, it's still a really great way to bootstrap things and get up and running quickly. I love the Gatsby plugin ecosystem but there's an open RFC in Next for the same thing. Next seems to be leaping over them in terms of features, performance, and developer experience. It's easier for Next to compete because they have a real company behind them that makes money from a myriad of products.

Anyways, I don't think Gatsby is going anywhere and it will continue to have a place. Just not necessarily for large sites. :)

**Comment by ZLevine** [comment]
Just tested and can confirm that MUI V5 functions correctly on the next branch! Thanks @hupe1980 and @oliviertassinari . Will log new issues if I run into anything else in development.
