### ISSUE TITLE
this plugin will break when upgrading to Material UI v5 rc due to renamed package to `@mui/*` 

### ISSUE THREAD

**Issue by kimbaudi** [hupe1980/gatsby-plugin-material-ui#75]
Material-UI renamed packages to `@mui/*` (see https://github.com/mui-org/material-ui/releases/tag/v5.0.0-rc.0) so migrating from mui v4 to v5 will break compatibility and cause error:

```raw
Can't resolve '@material-ui/styles' in '<path_to>\node_modules\gatsby-plugin-material-ui'

If you're trying to use a package make sure that '@material-ui/styles' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules\gatsby-plugin-material-ui\gatsby-browser.js:1:245
```

If/when upgrading to Material UI v5, you will need to change import from `@material-ui/styles` to `@mui/material/styles`

**Comment by hupe1980** [comment]
Have you tried the next branch?

**Comment by kimbaudi** [comment]
I just tried the next branch (v4.0.2) and I no longer get the error :tada:

closing this
