### ISSUE TITLE
Unable to define function in the theme object

### ISSUE THREAD

**Issue by lgollut** [hupe1980/gatsby-plugin-material-ui#9]
As per [Gatsby doc](https://www.gatsbyjs.org/docs/plugins/) 

> (...) plugin options will be stringified by Gatsby, so they cannot be functions

There is some case where defining functions in the theme object would be useful, in particular when dealing with the new `@material-ui/system` package to define some variant on a component as per [the official doc](https://next.material-ui.com/system/basics/#variants).

Here is a minimal example

```javascript
import { Button } from '@material-ui/core';
import { styled } from '@material-ui/styles';
import { style } from '@material-ui/system';

import { yellow, blue } = from './colors';

const variant = style({
  prop: 'gradient',
  cssProperty: false,
  themeKey: 'gradientButton',
});

const gradients = {
  primary: `linear-gradient(-61deg, ${yellow.light} 0%, ${yellow.dark} 100%)`,
  secondary: `linear-gradient(-61deg, ${blue.light} 0%, ${blue.dark} 100%)`,
};

const theme = {
  gradientButton: gradient => ({
    backgroundImage: gradients[gradient],
    color: '#fff',
  }),
};

const StyledButton = styled(Button)(variant);

<StyledButton gradient="primary">{'Gradient button'}</StyledButton>
```

A workaround would be to manually define every gradient objects under the `gradientButton` key but I can't remember if the Material-ui spec prohibits us to define functions in our custom theme object. Maybe @oliviertassinari can enlighten us on that point.

**Comment by oliviertassinari** [comment]
@lgollut Is this linked to Gatsby, could it be a more generic issue?

**Comment by lgollut** [comment]
I think it's really linked to how Gatsby stringifies plugins options. I just create a [codesandbox sample](https://codesandbox.io/s/y0lv4qvxn1) that work as expected.

**Comment by oliviertassinari** [comment]
I have started working on a first class support of Material-UI v4-alpha for Gatsby: https://github.com/mui-org/material-ui/tree/next/examples/gatsby-next. I'm using a different strategy for the theme, exactly like gatsby-plugin-typography where we use a theme.js file.

**Comment by lgollut** [comment]
Sounds good ! Thanks a lot Olivier

**Comment by oliviertassinari** [comment]
The theme option was removed from this plugin. I would encourage the usage of the ThemeProvider directly in user land.
